### ISSUE TITLE
Limited Storage Quota - Move away from Chrome.Storage.Sync

### ISSUE THREAD

**Issue by KathrynBrusewitz** [KathrynBrusewitz/type-new-tab#9]
Just realized there is a limit to how much can be stored in the sync storage area. From the [docs](https://developer.chrome.com/extensions/storage#property-sync), specifically only up to 102,400 bytes "as measured by the JSON stringification of every value plus every key's length". 

chrome.storage.local is much more generous, with up to 5,242,880 bytes or even unlimited storage with the unlimitedStorage permission set. But this removes the desired functionality for synchronous storage. Looking into mongodb and alternatives like the recently released Spaces by DigitalOcean.

**Comment by KathrynBrusewitz** [comment]
Even more reason to move away from Chrome storage, from reading this [StackOverflow answer](https://stackoverflow.com/a/26400590/7158628):

> Hitting quota limit may blacklist your extension in memory until Chrome is restarted.

> There is no way to wait for / request a sync. [...] And, as indicated by Chrome devs, that will probably stay this way.

Also, chrome.storage.sync API doesn't have any way to give the current status of Chrome Sync or if events were successful. According to this [feature request](https://bugs.chromium.org/p/chromium/issues/detail?id=361109):

> I don't think anyone from the sync team is going to work on this any time soon

That sucks :/

Currently writing up a notification toast to let user know they are reaching and have reached the quota limit, which on click opens modal for more information on why and what is being done about it, read as e.g. dedicated web app. Once pushed, will close this issue, update other issues, and start work on a web app version.

**Comment by jacksonbenete** [comment]
Hello @KathrynBrusewitz , what have you decided to do about sync storage limited size?
I'm seeing that you don't work on you project for a while, I have an extension that shares the same idea as your's, and have found this post searching for considerations about chrome.storage.sync limits.

**Comment by KathrynBrusewitz** [comment]
Hey @jacksonbenete . Yep, classes and work projects had me put this little project aside. Now that I've graduated and seeing there is some interest, I'll start working on the weekends where I last left off on Type.

To give a fully thought out answer, I'll have to refresh my mind by looking back at my old notes and research if anything changed in technologies over the past year in regards to extension storage solutions. So I'll reply again within the next few days with that. 

In the meantime, you can let me know what problem are you trying to solve and what are your use cases. Deciding how best to store your data depends a lot on what kinda features and support you need, e.g. synchronization, frequent updating/posting/pulling of small files versus infrequent posting/pulling of lots of data, are there plans to expand beyond the Chrome web browser (like an app or website) so an external storage solution is needed, etc. If your use cases are very simple, perhaps chrome.storage is really all you need.

**Comment by jacksonbenete** [comment]
I don't want to take your time @KathrynBrusewitz , but if you want I would love to talk about that.
I've graduated some years ago and had worked some years as a programmer and system analist in some companies. After some time I've decided to quit this kind of job and I stayed years away of programming and eletronic devices usage in general. I've spend some years even without a computer in my home. Now I'm starting to code again (non business related  stuff only) but realized that I forgot a lot of concepts, and there is much more new things that I'm not aware of.

I don't find yet any way of storage with chrome apps that avoid a VPN to host some kind of database or any other payed stuff, that's because I don't wanna charge for anything, in fact I don't even know if I will eventually release those apps because they lack a better design. The storage.sync seens nice, a free and easy persistence, but it may run out of storage space too fast. The problem is just this limited space.

I'm working in something just like your Type app as I've said before, it's an extension to customize new tab. It offer a way to write and save notes because Chrome OS lack notes app or even any simple text editor, and its also offer a toolbar with some buttons to open some web address or some Chrome OS apps. It's just a extension to fulfill my needs as a Chrome OS user.

![notes](https://user-images.githubusercontent.com/2954722/41205339-f79f5c02-6cc7-11e8-8764-f64b58145156.png)

Another project is an app to create and manage character sheets (from shadowrun roleplay game). This app supposed to dry storage limit even faster, especially if I start to attach images. For this I'm thinking about use xml support to persist and be able to import/export. But I've also wanted to sync for the convenience of recovering all informations instantly in a fresh install.

![fichashadowrun](https://user-images.githubusercontent.com/2954722/41205378-a23dcb6c-6cc8-11e8-949c-411d3155f3a6.png)

**Comment by jacksonbenete** [comment]
Hello there, I was not aware that Storage Sync wiped data after uninstall, that is it's "sync" like a local cache, if you uninstall the extension or if you go to a new device and load the extension there is no sync, no persistence.

I'll look for a way to use Drive API or functions to persist data like syncFileSystem. https://developer.chrome.com/apps/syncFileSystem

**Comment by KathrynBrusewitz** [comment]
Closing this issue, since I think this is out of scope for this little project. 
- Regarding lack of storage: I'm considering letting user know how many bytes they have left (or in percentage form)
- Regarding data persistence after an uninstall: out of scope in my opinion. syncFileSystem is now deprecated. If we persist to another DB, this might as well be a web app.
